### ISSUE TITLE
include path error

### ISSUE THREAD

**Issue by appotry** [bennycode/hexo-insert-markdown#6]
file path
source/_template/test.md

{% insertmd _template/test.md %}

but render error

**Comment by bennycode** [comment]
Hi @appotry, thanks for testing my plugin. Do you see a stacktrace to your error? Can you give me your "test.md" file so I can try to reproduce the problem myself? Best, Benny

**Comment by appotry** [comment]
`touch source/_template/test.md`
test.md is a blank file

```
00:25:06.818 FATAL {
  err: Template render error: (unknown path)
    TypeError: Cannot read properties of undefined (reading 'startsWith')
      at Object._prettifyError (/app/node_modules/nunjucks/src/lib.js:36:11)
      ... 11 lines matching cause stack trace ...
      at process.processImmediate (node:internal/timers:471:21) {
    cause: Template render error: (unknown path)
      TypeError: Cannot read properties of undefined (reading 'startsWith')
        at Object._prettifyError (/app/node_modules/nunjucks/src/lib.js:36:11)
        at /app/node_modules/nunjucks/src/environment.js:563:19
        at eval (eval at _compile (/app/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:67:12)
        at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
        at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
        at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
        at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)
        at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
        at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
        at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
        at Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:15:14)
        at process.processImmediate (node:internal/timers:471:21),
    isOperational: true
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```

env
```
# hexo -v
INFO  Validating config
hexo: 6.2.0
hexo-cli: 4.3.0
os: linux 5.10.60-qnap Debian GNU/Linux 11 (bullseye) 11 (bullseye)
node: 18.7.0
v8: 10.2.154.13-node.9
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 108
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.7
openssl: 3.0.5+quic
cldr: 41.0
icu: 71.1
tz: 2022a
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
···

plugin hexo-include-markdown installed,

**Comment by bennycode** [comment]
I just tried to reproduce your problem but for me it just works fine. Which hexo renderers are you using?

I use:

-     "hexo-renderer-ejs": "2.0.0",
-     "hexo-renderer-marked": "5.0.0",
-     "hexo-renderer-scss": "1.2.0",

**Comment by appotry** [comment]
my env
```
npm un hawk hexo-renderer-marked --force
npm install --save --force \
    hexo-renderer-markdown-it \
    markdown-it-latex2img \
    markdown-it-container \
    markdown-it-emoji \
    markdown-it-abbr \
    markdown-it-footnote \
    markdown-it-ins \
    markdown-it-sub \
    markdown-it-sup \
    markdown-it-mark \
    markdown-it-imsize


```

**Comment by bennycode** [comment]
Does it work when you enter content in the blank Markdown file?

**Comment by appotry** [comment]
source/_template/test.md
```
root@bdc87e661e4e:/app# cat source/_template/test.md              
## Test head
root@bdc87e661e4e:/app# 
```


err msg
```
node:internal/errors:704
  const ex = new Error(msg);
             ^

Error: socket hang up
    at connResetException (node:internal/errors:704:14)
    at TLSSocket.socketOnEnd (node:_http_client:505:23)
    at TLSSocket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ECONNRESET',
  response: undefined
}

Node.js v18.7.0
```

**Comment by bennycode** [comment]
I am sorry but I cannot reproduce your problem to help you further. 😓 It also seems that something else is crashing as my plugin name doesn't show up in your error messages. 

This is how I am using the plugin in my Hexo blog:

**source/errors/index.md**

```
{% insertmd errors/includes '---' '{ "max_depth": 2 }' %}
```

And then I have several `*.md` files inside the `source/errors/includes` directory.

I am using: "hexo-insert-markdown": "1.4.2"

Please reopen the ticket if you have any additional logging messages for me that could help finding the problem on your end.

Best,
Benny
